---
title: "Appreciative Advising"
subtitle: "Chapters 4 (Disarm), 5 (Discover), and 6 (Dream)"
output:
  ioslides_presentation:
    incremental: true
    smaller: true
---

# Disarm: Make a positive first impression with students by creating a safe and welcoming environment

## Key Features of the Disarm Phase

- Warm welcome
- Safe and comfortable environment
- Appropriate self-disclosure
- Appropriate nonverbal behavior

<div class="notes">

- Importance of acknowledgment---full frontal stance and smile
  - Challenges during virtual meetings:  turning on video, when possible; being cognizant of posture, etc.
- Minimizing distractions; safe and comfortable seat (our campus offices don't always feel "comfortable")
- Sharing a funny story to lighten the mood?
- Don't cross arms!
-*Authenticity*
-*Asset-based stories*
-*Sincerity* (sharing, not teaching/preaching)
- Tool-box:  self-reflection questions?

</div>

# Discover: Build rapport through positive, active questioning that draws out students' strengths, passions, and skills

## Key Features of the Discover Phase

- Effective, open-ended questioning
- Attending behavior and active listening
- Strength-based story reconstruction

<div class="notes">

- Share examples of open-ended questions (hobbies, what did they dream of "being" when they were young?)
- Appreciative Advising Inventory (Appendix A, p. 159); allows students/advisors to identify student's assets
- Appendix B (p. 163):  follow-up questions to AA Inventory
- Attending behavior:  visual (eye contact), vocal qualities (tone/rate of speech), verbal tracking (sticking to subject), and body language
- Paraphrasing/summarizing; picking up on student's strengths
- Taking notes (Table 5.1, p. 52)

</div>

# Dream: Use students' hopes and dreams to help them create positive mental images of their futures

## {data-background="https://upload.wikimedia.org/wikipedia/commons/4/49/Deep-dream-white-noise-0050.jpg" data-background-size=cover}

## Key Features of the Dream Phase

- Creating powerful images
- Prospective framework for dreaming
- Making purposeful connections between the Dream and Discover phases